# Generated by Django 2.0.2 on 2018-04-10 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('career', django_mysql.models.JSONField(default=dict, null=True)),
                ('training', django_mysql.models.JSONField(default=dict, null=True)),
                ('cv_ref', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=20, null=True)),
                ('salary', models.CharField(max_length=20, null=True)),
                ('degree', models.CharField(max_length=10, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('technologies', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('qualities', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='joboffer',
            name='recruter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Recruter'),
        ),
    ]
